eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-feign-consumer-hystrix
feign:
  hystrix:
    enabled: true


